// GENERATED by scripts/gen-migrations-manifest.ts — do not hand-edit; it's rewritten on every build.
export const MIGRATION_FILES = [
  "0001_schema.sql",
  "0002_drop_class_motto.sql",
  "0003_drop_principal_open.sql",
  "0004_team_play.sql",
  "0005_note_spend_snapshot.sql",
  "0006_math_challenge.sql",
  "0007_buzzer.sql"
] as const;
