import fs from "node:fs";
import path from "node:path";

/**
 * Regenerates src/lib/db/migrations-manifest.ts from the real contents of supabase/migrations/.
 * Runs automatically before every `npm run build`/`npm run dev` (see package.json's "predev"/"prebuild"),
 * so /api/health's "tables up to date" check always knows the true, current list of migrations this
 * BUILD needs — without a human remembering to update a hardcoded filename. (Twice, now, a hand-maintained
 * one went stale and let that check report "ok" on a database that wasn't: see git history on
 * src/app/api/health/route.ts. Migration files aren't otherwise bundled with the deployed site, so the
 * route can't just list the folder itself at runtime — this generated, imported constant is what is.)
 */
const dir = path.join(process.cwd(), "supabase", "migrations");
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
const out = path.join(process.cwd(), "src", "lib", "db", "migrations-manifest.ts");
fs.writeFileSync(
  out,
  `// GENERATED by scripts/gen-migrations-manifest.ts — do not hand-edit; it's rewritten on every build.\n` +
    `export const MIGRATION_FILES = ${JSON.stringify(files, null, 2)} as const;\n`,
);
console.log(`Wrote ${out} (${files.length} migrations).`);
